### ISSUE TITLE
Document Autoware Universe ROS nodes for the Perception stack

### ISSUE THREAD

**Issue by kaspermeck-arm** [autowarefoundation/AutowareProjects#34]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

List all ROS nodes in Autoware.Universe with the following information
- feature
- ROS messages/topics
- software dependencies, e.g., compute libraries (BLAS), GP-GPU, etc.

### Purpose

For Autoware to be deployed as a microservices architecture, the 
- software dependencies
- communication
- implemented feature

of each ROS package/node needs to made available for users of Autoware. This is necessary to create a container image which satisfies the runtime dependencies.

### Possible approaches

Ideas:
- use colcon list/graph
- create a visual picture of how nodes communicate (ROS messages and topics)
- add an explanation of how to use `colcon graph` to Autoware documentation

### Definition of done

- [x] When information necessary to group ROS packages/nodes together in container images in a compatible way is made accessible.
- [x] An explanation of how to use `colcon graph`, along with a small example of the expected output has been added to Autoware documentation

**Comment by kenji-miyake** [comment]
FYI, here is the node configuration diagram of TIER IV's proposal created by @TakaHoribe.
https://tier4.github.io/autoware-documentation/latest/design/node-diagram/#autoware-universe

Since it's just a proposal from TIER IV yet, we currently put it in our fork.

**Comment by ghost** [comment]
> FYI, here is the node configuration diagram of TIER IV's proposal created by @TakaHoribe. https://tier4.github.io/autoware-documentation/latest/design/node-diagram/#autoware-universe

@mitsudome-r @xmfcx Last week we confirmed that perception was the first component that we wanted to get information about, so is the diagram above an accurate representation of the ROS nodes required for perception?

Also, does the diagram show all of the inputs/outputs for each node, or is just an overview?

**Comment by mitsudome-r** [comment]
Here's the list of packages dependency of perception modules:
![graph](https://user-images.githubusercontent.com/43976834/171442988-be97c0a3-85f8-4fe4-87ab-0fd9c7939f4d.png)

And here is the list of the packages in the graph:
```
autoware_auto_geometry_msgs
autoware_auto_mapping_msgs
autoware_auto_perception_msgs
autoware_auto_planning_msgs
autoware_auto_vehicle_msgs
autoware_cmake
autoware_lint_common
autoware_point_types
compare_map_segmentation
detected_object_feature_remover
detected_object_validation
detection_by_tracker
euclidean_cluster
grid_map_cmake_helpers
grid_map_core
grid_map_cv
grid_map_msgs
grid_map_pcl
grid_map_ros
ground_segmentation
image_projection_based_fusion
image_transport_decompressor
interpolation
kalman_filter
lanelet2_extension
lidar_apollo_instance_segmentation
map_based_prediction
multi_object_tracker
mussp
object_merger
object_range_splitter
occupancy_grid_map_outlier_filter
pointcloud_preprocessor
pointcloud_to_laserscan
shape_estimation
tensorrt_yolo
tier4_autoware_utils
tier4_debug_msgs
tier4_pcl_extensions
tier4_perception_launch
tier4_perception_msgs
traffic_light_classifier
traffic_light_map_based_detector
traffic_light_ssd_fine_detector
traffic_light_visualization
vehicle_info_util
```

**Comment by xmfcx** [comment]
@mitsudome-r could you share the command you used to create this graph too?

**Comment by xmfcx** [comment]
> Here's the list of packages dependency of perception modules:

@mitsudome-r I think these are dependencies of planning stack, not perception.

**Comment by mitsudome-r** [comment]
@xmfcx Thanks, I posted the wrong image. I've modified the image with the correct one.
The list should be the ones from perception stack.

Here's the command that I used.
* To generate the graph: ` colcon graph --dot --packages-up-to tier4_perception_launch | dot -Tpng -o graph.png`
* To generate the list `colcon list --packages-up-to tier4_perception_launch`

**Comment by mitsudome-r** [comment]
FYI: I had to modify package.xml in tier4_perception_launch to create correct dependency graph.
https://github.com/autowarefoundation/autoware.universe/pull/1024

**Comment by kaspermeck-arm** [comment]
@mitsudome-r 
Is there some way to see which topics ROS nodes publish and subscribe to?

**Comment by mitsudome-r** [comment]
You can just run the launch file and check it with rqt_graph.
e.g.,
`ros2 launch tier4_perception_launch perception.launch.xml mode:=lidar`
`ros2 run rqt_graph rqt_graph`

**Comment by ghost** [comment]
@kasperornmeck Since the necessary commands have been provided, could you write up this information and submit a PR to the [autoware-documentation](https://github.com/autowarefoundation/autoware-documentation) repository?

The ["How to guides" section](
https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/) covers more advanced topics and so this would be the best place to write up a guide on how to list all the required packages and dependencies for a specific stack.

**Comment by ghost** [comment]
PR created to add the information in this issue to Autoware documentation:
https://github.com/autowarefoundation/autoware-documentation/pull/162
