### ISSUE TITLE
Create an Open AD Kit documentation site

### ISSUE THREAD

**Issue by ghost** [autowarefoundation/AutowareProjects#35]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Create a documentation site for Open AD Kit

### Purpose

At present, documentation for the Open AD Kit project is minimal, and the documentation that does exist is currently hosted on GitLab. As a foundation for better documentation going forwards, a documentation repository should be created and configured appropriately, before migrating all existing documentation to this site.

### Definition of done

- [x] Create an Open AD Kit documentation repository in the AWF org on GitHub
  - https://github.com/autowarefoundation/open-ad-kit-docs
- [x] Mirror the CI/CD configuration that is used by other Autoware documentation sites 
- [x] Set up a GitHub pages site so that the documentation can be accessed
- [x] Copy the Open AD Kit v1.0 quick start guide from GitLab to the new GitHub repository

**Comment by kenji-miyake** [comment]
@LalithVipulananthan Should I help with something around these items?
> Mirror the CI/CD configuration that is used by other Autoware documentation sites
> Set up a GitHub pages site so that the documentation can be accessed

**Comment by ghost** [comment]
@kenji-miyake Aha! I missed your comment and just asked you about this via Slack. If you could assist with those steps then that would be very much appreciated!

**Comment by kenji-miyake** [comment]
@mitsudome-r @xmfcx @BonoloAWF Could someone approve to install `awf-autoware-bot` to https://github.com/autowarefoundation/open-ad-kit-docs? :pray: It seems I need approval from an org admin. I guess you've received an email from GitHub.
https://github.com/organizations/autowarefoundation/settings/apps/awf-autoware-bot

-> Mitsudome-san has approved. Thank you!

**Comment by kenji-miyake** [comment]
@LalithVipulananthan I've changed the settings of GitHub Pages. You have to use `gh-pages/root` instead of `main/docs` to show the site built by MkDocs.

![image](https://user-images.githubusercontent.com/31987104/172605553-d4b9ffda-f6ca-4e10-88d3-58b190f62c0f.png)

**Comment by ghost** [comment]
Closing as complete since the documentation repository was created and there is a public-facing website which has the documentation for Open AD Kit 1.0. 

Repository: https://github.com/autowarefoundation/open-ad-kit-docs
Website: https://autowarefoundation.github.io/open-ad-kit-docs/latest/
