### ISSUE TITLE
Update documentation site to add OADK 2.0 installation instructions

### ISSUE THREAD

**Issue by ghost** [autowarefoundation/AutowareProjects#46]
## Description

Now that the OADK [documentation repository](https://github.com/autowarefoundation/open-ad-kit-docs) and [website](https://autowarefoundation.github.io/open-ad-kit-docs/latest/) have been set up to explain setup and installation for the AVA Dev Platform and AutoCore PCU with Autoware.Auto, we need to add installation and setup instructions for OADK 2.0 with Autoware Universe running on those two platforms plus additional platforms (AGX Orin and AGX Xavier).

### Purpose

To maintain the documentation site with the most up-to-date information for Autoware Universe and tested/verified platforms, and to improve the visibility of the OADK and encourage greater usage.

### Definition of done  

- [x] Update the repository such that it is possible to have multiple versions of the OADK's installation and setup instructions @d-hashimoto 
- [ ] Add setup instructions for Autoware Universe on the AVA Dev Platform @ito-san 
- [ ] Add setup instructions for Autoware Universe on the AutoCore PCU @Sharrrrk 
- [ ] Add [setup instructions for Autoware Universe on the AGX Orin](https://github.com/autowarefoundation/autoware-projects/issues/32#issuecomment-1226676657) @Sharrrrk
- [ ] Add setup instructions for Autoware Universe on the AGX Xavier @Sharrrrk 
- [ ] Add [setup instructions to run multiple Autoware Universe containers orchestrated by K3s on the AVA Dev Platform](https://github.com/autowarefoundation/open-ad-kit-docs/blob/proposal_v2.0/docs/start-guide/installation/advanced-setup-setup-ava.md) @ito-san

**Comment by ghost** [comment]
@Sharrrrk Hi Shark, would it be possible to re-export your AutoCore PCU and AGX Xavier test reports for Autoware Universe please, such that all of the command line output can be seen. Like before with the AGX Orin test report, there are a lot of commands that have been cut off in the exported PDF.

PCU test report: https://github.com/autowarefoundation/autoware-projects/issues/32#issuecomment-1203436130
AGX Xavier test report: https://github.com/autowarefoundation/autoware-projects/issues/32#issuecomment-1212959421

**Comment by ghost** [comment]
> Update the repository such that it is possible to have multiple versions of the OADK's installation and setup instructions

After [this PR](https://github.com/autowarefoundation/open-ad-kit-docs/pull/27) is merged, it will be done.

**Comment by evshary** [comment]
I've tried to sync the OADK 2.0 documentation site with branch proposal_v2.0 in [this PR](https://github.com/autowarefoundation/open-ad-kit-docs/pull/31).
Updating the tutorial to the latest version on the documentation site will help developers to find the tutorial much easier.
It'll be great if someone can help me to review the PR.

**Comment by evshary** [comment]
> Add setup instructions for Autoware Universe on the AVA Dev Platform

I've verified the OADK 2.0 tutorial on the documentation site, and I'm able to install & run scenario simulator successfully.

**Comment by BonoloAWF** [comment]
@evshary can this Issue be closed given that https://github.com/autowarefoundation/open-ad-kit-docs/pull/31 is merged?

**Comment by evshary** [comment]
@BonoloAWF For AVA platform, I think the answer is yes.
And I found that Autocore has also put Xavier platform into the documentation
https://github.com/autowarefoundation/open-ad-kit-docs/pull/38
Therefore, in my opinion, maybe this issue can be closed now, but I'm not sure whether there are any concerns from others.
