### ISSUE TITLE
OpenSCENARIO format support in AWSIM

### ISSUE THREAD

**Issue by WJaworskiRobotec** [autowarefoundation/AutowareProjects#60]
Integration of scenario simulator v2 with AWSIM,
to enable execution of OpenSCENARIO based 
scenarios in AWSIM

**Comment by WJaworskiRobotec** [comment]
SS2 architecture is adjusted to work with AWSIM : https://github.com/tier4/scenario_simulator_v2/pull/969

**Comment by piotr-zyskowski-rai** [comment]
Additional PRs were merged to support the connection to AWSIM
- https://github.com/tier4/scenario_simulator_v2/pull/998
- https://github.com/tier4/scenario_simulator_v2/pull/1028
- https://github.com/tier4/scenario_simulator_v2/pull/1058

Connection stability issues were fixed on the AWSIM side

The connection is now functional. Scenarios tests are in progress


https://github.com/autowarefoundation/autoware-projects/assets/87643052/b7804b36-636e-4097-adf8-1b9ac0dc2af2

**Comment by WJaworskiRobotec** [comment]
Feature is merged : https://github.com/tier4/AWSIM/pull/219

**Comment by mackierx111** [comment]
I will publish a tutorial in the next release (v1.2.0).
https://github.com/tier4/AWSIM/pull/229
